name: check-api
on: [push, pull_request]
permissions:
  checks: write
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Create Check Run
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -L -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $GH_TOKEN"\
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/check-runs \
            -d '{"name":"check_actions", "head_sha":"${{ github.event.pull_request.head.sha }}", "status":"in_progress","output":{"title":"check_actions", "summary": "check_actions", "text": "checkしてくれい"},"actions":[{"label":"checked", "description":"please check", "identifier":"check" }]}'
      - name: Post a comment to the PR
        run: |
          PR_NUMBER="${{ github.event.pull_request.number }}"
          
          # Issues APIでコメントを投稿
          curl -X POST \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/issues/$PR_NUMBER/comments \
            -d '{"body": "Hello from GitHub Actions!"}'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

