name: handle-check-run-action
on:
  check_run:
    types: [requested_action]

jobs:
  handle_button_click:
    runs-on: ubuntu-latest
    permissions:
      checks: write

    steps:
      - name: Handle requested_action
        run: |
          ACTION_ID="${{ github.event.requested_action.identifier }}"
          CHECK_RUN_ID="${{ github.event.check_run.id }}"

          echo "Button clicked: $ACTION_ID"
          echo "Check Run ID: $CHECK_RUN_ID"

          if [ "$ACTION_ID" = "check" ]; then
            CONCLUSION="success"
            TITLE="Approved!"
            SUMMARY="Thank you! This check is successful now."
          else
            CONCLUSION="failure"
            TITLE="Rejected!"
            SUMMARY="The check was marked as failed."
          fi

          curl -s -X PATCH \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/check-runs/$CHECK_RUN_ID \
            -d "{
              \"status\": \"completed\",
              \"conclusion\": \"${CONCLUSION}\",
              \"output\": {
                \"title\": \"${TITLE}\",
                \"summary\": \"${SUMMARY}\"
              }
            }"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

